### ISSUE TITLE
What if we can go to the line which we highlighted?

### ISSUE THREAD

**Issue by Vui-Chee** [lpinilla/vim-codepainter#11]
**Describe the solution you'd like**
Hi, first of all, I love your plugin! It is really useful especially reading text in Vim. But I am wondering, if it is possible for someone to navigate to any line that was highlighted by your plugin? 

For instance, I have some highlights in line 45, and I am currently at line 687. But I forgot that I highlight some text at line 45. So to navigate to this line, we can have a command that opens a preview window that lists the current _highlights_ in the file. And upon selection can we then navigate to the line where the highlight occurs.

**Describe alternatives you've considered**
I tried `MattesGroeger/vim-bookmarks` but only marks lines without the ability to highlight multiple sub-patterns in the same line.

So it is like having marks in Vim but more awesome since you can highlight any text, and this plugin will also mark its location.

**Comment by lpinilla** [comment]
Hi! Sorry for the late response. First of all thanks for your words and interest on this project :smile:  

Regarding the feature request, I like the idea. Although I'm not sure, I think both vim's text properties and neovim's builtin function mark the text besides giving the highlight. So it would be a matter of navigating through those marks. It could be an interesting feature to navigate through highlights.

**Comment by Vui-Chee** [comment]
Awesome, no worries. When I have the time, I am going to experiment this feature. 

For now I will close this till a more apparent feature is decided and proven possible.

**Comment by lpinilla** [comment]
You can leave it open if you want, I plan to implement this on the near future
