### ISSUE TITLE
PainterEraseCurrentLine

### ISSUE THREAD

**Issue by pacmanzou** [lpinilla/vim-codepainter#14]
Hi, your plugin is great, but
Every time I use PainterEraseLine I have to enter a number, which is troublesome, especially when used frequently.
Why not add a PainterEraseCurrentLine to it to automatically clear the current line of the cursor painting.
I can't use Vimscript, so I can't write it. Could you please try to write it? Thank you very much!

**Comment by pacmanzou** [comment]
Hi! Thanks for your reply,
But I'm so sorry, I can't quite understand your answer. I am a Chinese and my English is not very good. I just need a function that can clear the current line marker where the cursor is located.I think this feature will remove the marks faster.

**Comment by lpinilla** [comment]
Oh sure, no problem!
