### ISSUE TITLE
absolut path of json file

### ISSUE THREAD

**Issue by juanMarinero** [lpinilla/vim-codepainter#20]
**Describe the bug**
This works
```
:PainterSaveMarks file.json
:PainterLoadMarks file.json
```
This does NOT work
```
:PainterSaveMarks /home/user/folder/file.json
:PainterLoadMarks /home/user/folder/file.json
```
If I read the saved json file, it outputs E121:

```

Error detected while processing function codepainter#SaveMarks:
line    9:
E121: Undefined variable: file{"1":[[[0,1,57,0],[0,1,72,0],0,"paint0"]]}
```

**Desktop:**
 - OS: Ubuntu 20.04
 - Vim 8.2

Thanks in advance!

**Comment by lpinilla** [comment]
I've tested both in neovim and vim version 8.1 and saving the file does work for absolute paths.

This will require more testing as I don't see the work `file` on the saved file, maybe something changed on vim version 8.2

**Comment by lpinilla** [comment]
I've tested saving marks to an absolute path with the same setup and it did work.

 I'm closing this issue but feel free to open it again if the trouble continues

**Comment by juanMarinero** [comment]
Hi @lpinilla 
You are right. I cannot longer reproduce my own reported error (shame on me).

I guess on that day I did not just run the `PainterSaveMarks` alone, but with and appended `| echo "blabla"`. That way I still get same error (`E121`), that has no relation with absolute/relative path of json file. See https://github.com/lpinilla/vim-codepainter/pull/18#issuecomment-835865853 please.

Very well done testing it in Vim 8.2 and closing current issue, thanks! Gracias! 👏
