### ISSUE TITLE
color inspection under cursor just like vs code

### ISSUE THREAD

**Issue by alexzanderr** [lpinilla/vim-codepainter#21]
hey. nice plugin.

how about making a feature to inspect to colors with `<C-i>` just like in vs code?

when i do `<C-i>` in vs code i get a little pop-up window information about `background color`, `foreground color` and other useful  information:
![image](https://user-images.githubusercontent.com/54772464/125294314-d49c2080-e32c-11eb-96f3-a44bcb24674e.png)

this would be useful when i want to:
- see the colors of a theme
- creating themes
- working with themes

waiting for an answer. thanks.

**Comment by lpinilla** [comment]
Hi! thanks for the suggestion :D 

Although I see how it could be helpful, it still doesn't convince me the fact that the colors are pre-defined and you can just go at the config file and look at their value. 

If I'm not mistaken, it is pretty doable but I'm debating whether or not it justifies creating an emerging window when you can go and lookup the predefined colors. Maybe I don't see the "helpful-ness" as I'm not someone who plays a lot with color-schemes.

Did you find yourself in the recurrent situation that this was something you needed?

**Comment by alexzanderr** [comment]
yes, i find myself in the situation, thats why i started this issue (feature request).

sometimes i edit colors schemes, and its very easy to go and see the color under cursor, because maybe you like it and you want to use it in your custom color scheme or maybe you want to update a variable in an existing color scheme with that color.

however, the decision is yours, i asked for your help because i saw the complexity of this plugin with highlithing and i thought that my idea is going to be easy for you.

**Comment by lpinilla** [comment]
I see, I'll investigate if the pop-up can be easily incorporated. Otherwise, there can be a new command to call on cursor position on with a remap

**Comment by alexzanderr** [comment]
thank you very much

**Comment by lpinilla** [comment]
I think this can be a cool separate plugin, so I won't add it to this project
