### ISSUE TITLE
Toggle highlight

### ISSUE THREAD

**Issue by hbarcelos** [lpinilla/vim-codepainter#22]
**Is your feature request related to a problem? Please describe.**
Currently when using the default <kbd>F2</kbd> mapping works only to create a highlight.

**Describe the solution you'd like**
It would be even more awesome if we could toggle the highlight with the same key. Press <kbd>F2</kbd> once and highlight is enabled. Press it again and it's gone.

**Describe alternatives you've considered**
I tried to look at the internals of the plugin to see if there was an easy way to check if the current line/range is currently highlighted in order to write the toggle condition myself, but I'm not that much proficient in Vimscript and I couldn't figure out a way to do that.

**Additional context**
It would be great if it worked for visual mode and ranges as well. There could be a simple heuristic that if all the selection/range is currently highlighted, then the highlight is removed, otherwise, everything currently selected become highlighted.

**Comment by lpinilla** [comment]
Hi!
Thank for your suggestion,

I'm not quite sure of the toggle functionality, you mean a button to show/hide all highlights? or to be able to remove a highlight?

The second one is already implemented, if you highlight a word and then select it and highlight it again, it will clean it.

Now if you are talking about highlighting a word and hide it without removing.. that could be more difficult to do as there needs to be a state of "is_hidden" or something like that.

Although this brings the idea of being able to toggle between different colors.. that could be interesting...
