### ISSUE TITLE
First line of the document cannot be erased

### ISSUE THREAD

**Issue by louis-vinchon** [lpinilla/vim-codepainter#23]
**Describe the bug**

Neither `PainterEraseAll` or `PainterEraseLine` are capable of removing the "paint" on the very first line of the document.

**To Reproduce**
1. Select the first line, paint it with `F2`.
2. Run `:PainterEraseAll`.
3. Run `PainterEraseLine`.

**Expected behavior**
The paint is cleared just like on any other line.

**Comment by lpinilla** [comment]
Hey! Thanks for the info, I'll be looking into it

**Comment by K41eb** [comment]
Yup, works much better. Thank you for the fix.
