### ISSUE TITLE
Using PainterEraseAll or PainterEraseLine in a split pane breaks it for other panes

### ISSUE THREAD

**Issue by K41eb** [lpinilla/vim-codepainter#24]
**Describe the bug**
When using `PainterEraseAll` or `PainterEraseLine` in a pane, going to an other pane, and then using the commands again, they no longer work for this pane.

**To Reproduce**
1. Open any document.
2. Paint a line.
2. Open an other document in a split pane with `:vs` or `:sp`.
3. Paint a line.
4. Use `:PainterEraseAll` or `:PainterEraseLine` in either one of the splits.
5. Go to the other split and try to use the same commands. The paint should remain despite the commands.

**Expected behavior**
Erasing works in any pane.

**Comment by lpinilla** [comment]
Please specify program version.

I've tested it on neovim following the steps and it works as espected.

Closing it for now until there is more evidence

**Comment by K41eb** [comment]
It was fixed in a more recent version yes.
