### ISSUE TITLE
Coloring moves to different line when lines above are added/deleted

### ISSUE THREAD

**Issue by pinaki2** [lpinilla/vim-codepainter#27]
**Describe the bug**
If we have certain lines colored and then we add or delete other lines above colored lines, then the code we previously colored does not remain colored any more. Instead, other lines of code that currently occupy the same lines are now colored. Looks like currently text is colored based on line number

**To Reproduce**
1. Open an existing file containing 2 or more lines.
2. Color any line (except line 1).
3. Add or delete line(s) in any section above the colored line.
4. The same text is no longer colored.

**Expected behavior**
The same text should still remain colored.

**Comment by lpinilla** [comment]
Hi, this is kind of a "it's a feature, not a bug" because the way to "follow" the text is quite more complex (involves using vim marks) than the way it works right now.

As for now, it won't be changed for this behavior but I don't discard it for the future.

Thank you for your report!
